project_root: /workspace/t2024/
geo_reference_json: /workspace/t2024/LoG/my_data/US-NewYork-Queens-10-Center-Blvd-R375-A410/US-NewYork-Queens-10-Center-Blvd-R375-A410_rotated.json
topdown_view_parameter:
  rotated_angle: 282
  height: 2048
  width: 2048
  one_side_meter: 515
topdown_seglist_json: /workspace/t2024/LoG/renders4visprog/querys_topdown_seg_list.json
request_similar_area_json: /workspace/t2024/LoG/renders4visprog/request_similar_area_json.json
process_finish_flag: /workspace/t2024/LoG/renders4visprog/process_finish.txt
similarity_wake_flag_path: /workspace/t2024/geoprog3d/similarity_process_wake.txt
similarity_count_json: /workspace/t2024/geoprog3d/similarity_count.json
counting_wake_flag_path: /workspace/t2024/geoprog3d/counting_process_wake.txt
height_wake_flag_path: /workspace/t2024/geoprog3d/height_process_wake.txt

scene_info:
  scene_name: US-NewYork-Queens-10-Center-Blvd-R375-A410
  config_path: /workspace/t2024/LoG/config/citygen/my_test_pepsi/train.yml
  dataset_path: /workspace/t2024/LoG/config/citygen/my_test_pepsi/dataset.yml
  ckpt_path: /workspace/t2024/LoG/output/citygen/US-NewYork-Queens-10-Center-Blvd-R375-A410/3dgs/model_tree.pth
  ckpt_colors_path: /workspace/t2024/LoG/output/citygen/US-NewYork-Queens-10-Center-Blvd-R375-A410/3dgs/model_tree_colors.pth
  renders_npy: /workspace/t2024/LoG/renders4visprog/<scene>/renders_npy/
  camera_param:
    topdown: x=-24.532743647866504, y=-256.71059084564786, z=-280.0, yaw=-89.63100000000006, pitch=-0.7440000000000005, roll=0.0, image_size=(2048, 2048), focal_length=150000.0, scale=1.0, znear=0.001, zfar=14000.0
    arbitrary: 
        - x=-7.711493750950513, y=20.410057935210133, z=-400.0, yaw=-95.39999999999998, pitch=0.047999999999999994, roll=0.0, image_size=(1024, 1024), focal_length=102400.0, scale=1.0, znear=0.001, zfar=11000.0
        - x=-7.223107231440617, y=21.59222297860297, z=-400.0, yaw=-95.42999999999999, pitch=0.049999999999999996, roll=0.0, image_size=(1024, 1024), focal_length=307200.0, scale=1.0, znear=0.001, zfar=11000.0
        - x=-9.54924952348043, y=19.395773383400872, z=-400.0, yaw=-95.31, pitch=0.049999999999999996, roll=0.0, image_size=(1024, 1024), focal_length=360000.0, scale=1.0, znear=0.001, zfar=11000.0
    eval_index_list: [0,1,2]
    arbitrary_height: 1024
    arbitrary_width: 1024

filtering_gaussian: False

get_sim_param:
  mask_thresh: 0.3
  heatmap_thresh: 128
  adjust_gs_axis: True
  ae_ckpt_path: /workspace/t2024/LangSplat/ckpts/US-NewYork-Queens-10-Center-Blvd-R375-A410/best_ckpt.pth
  ae_encoder_dims: [256, 128, 64, 32, 3]
  ae_decoder_dims: [16, 32, 64, 128, 256, 256, 512]

grounding_dino_param:
  pyfile: /workspace/t2024/counting/GroundingDINO_SwinT_OGC.py
  weight_path: /workspace/t2024/counting/groundingdino_swint_ogc.pth
  box_threshold: 0.5